# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins

# could be useful vv, but not in accept list ^^ :(
# https://github.com/jekyll/jekyll-sitemap
# https://github.com/jekyll/jekyll-feed

markdown_ext: "nope"
